### ISSUE TITLE
Auto Refund 72 hours after complete booking if no dispute created 

### ISSUE THREAD

**Issue by PrenSJ2** [PrenSJ2/teamworks_api#19]
i have created a attribute of trip called
`isRefunded`

adjust the `refund_deposit` endpoint to on completion of refund set `isRefund` to true,

also add a second part to the auto-complete code you added last time.

if `complete` and !`isRefunded` and trip end time is 72 hours ago, call the refund deposit function with amount = 0, to give a full refund of the deposit

**Comment by nicaprentice** [comment]
add another attribute:
when stripe returns an error saying payment doesnt exist, add return statement
